name: CI on Windows

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    name: Windows / Perl latest
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry
          perl-version: latest

      - shell: pwsh
        run: perl -V

      - shell: pwsh
        run: |
          cpanm --notest --installdeps .

      - shell: pwsh
        env:
          AUTOMATED_TESTING: 1
          NONINTERACTIVE_TESTING: 1
        run: |
          perl Makefile.PL
          gmake test
